-- seed_db.sql -- regenerated to match current schema.sql
-- (cat_num/loc_num FKs instead of item_cat/box_loc strings).
-- Generated by migrate_seed.py from the old string-based seed dump.
-- item_pic filenames are unchanged -- still matches seed_images.zip.

SET FOREIGN_KEY_CHECKS=0;

DELETE FROM `categories`;
INSERT INTO `categories` (`cat_num`, `cat_name`) VALUES
(0,'Uncategorized'),
(1,'Decorating'),
(2,'Wall decor'),
(3,'Kitchen');

DELETE FROM `locations`;
INSERT INTO `locations` (`loc_name`, `loc_num`) VALUES
('Unspecified',0),
('Storage room',1);

DELETE FROM `boxes`;
INSERT INTO `boxes` (`box_num`, `loc_num`, `box_name`, `box_date`, `box_last_changed`) VALUES
(1,1,'','2025-08-05','2025-08-05'),
(2,1,'','2025-08-05','2025-08-05'),
(3,1,'','2025-08-17','2025-08-17'),
(4,1,'','2025-08-18','2025-08-18'),
(5,1,'','2025-08-20','2025-08-20'),
(6,1,'','2025-08-22','2025-08-22'),
(7,1,'','2025-08-22','2025-08-22'),
(8,1,'','2026-06-25','2026-06-25'),
(9,1,'','2026-06-27','2026-06-27');

DELETE FROM `items`;
INSERT INTO `items` (`item_num`, `item_name`, `box_num`, `item_pic`, `item_date`, `cat_num`, `item_desc`) VALUES
(1,'Snail','1','IMG_22601753393961.3702104.jpeg','2025-07-24',1,'Brown/Metal/Textured/Heavy'),
(2,'Owl','1','IMG_22611753394194.336892.jpeg','2025-07-24',1,'Resin/Charcoal Gray/Tall/Smith & Hawken'),
(3,'8x10 Empty Clip Frame','2','IMG_46681753395665.9701016.jpeg','2025-07-24',2,'Landscape or Portrait Frame'),
(4,'8x10 Tree Sketch in Black Frame','2','image1753395949.0935495.jpg','2025-07-24',2,'Michelle Dujardin/Portrait Frame/Botanical Art'),
(5,'11x14 Set of Two Botanical Prints in Clip Frames','2','IMG_46691753396298.3462243.jpeg','2025-07-24',2,'Blue/Eucalyptus/Prints from Digital File/Landscape or Portrait Frame/Botanical Art'),
(6,'8x10 Set of Five Owl Prints in Wood Frames','2','IMG_46701753397201.030576.jpeg','2025-07-24',2,'With Mat/Hand Colored/West Elm/Wall or Tabletop/Landscape or Portrait Frame'),
(7,'8x10 Set of Five Tree Sketches in Clip Frames','2','IMG_46711753398546.7061813.jpeg','2025-07-24',2,'Michelle Dujardin/Live Oak/California Pepper/Eucalyptus/Landscape or Portrait Frame/Botanical Art'),
(8,'8x10 Set of Three Victorian Bathroom Prints in Clip Frames','2','image1753399086.805977.jpg','2025-07-25',2,'Landscape or Portrait Frame/Photographic Art'),
(9,'Lacquer Tray (white) with Handles','3','image1753476102.1781511.jpg','2025-07-25',1,'White with Silver/Bird Silhouette/Botanical/Lacquer/Square'),
(10,'Large Decorative Bowl','3','IMG_46721753477082.2774763.jpeg','2025-07-25',1,'Multicolor/Yellow/Teal/Green/Red/White/Floral/Botanical/Pier One/Coordinating Pitcher'),
(11,'4.5 Quart Mixing Bowl with Lid ','3','image1753477795.458188.jpg','2025-07-25',3,'Pyrex/Clear'),
(12,'Set of Two Fluted Serving Bowls','3','image1753478006.6755762.jpg','2025-07-25',3,'Pier One/Nesting/White'),
(13,'Large Glass Plate with Beaded Edge','3','IMG_46741753478575.6694102.jpeg','2025-07-25',3,'Clear'),
(14,'Large Decorative Glass Bowl','3','IMG_46751753478716.8615396.jpeg','2025-07-25',1,'Clear/Spiral'),
(15,'Bread Basket with Warming Stone','3','image1753479191.8827608.jpg','2025-07-25',3,'Rectangular/Cotton Cloth Liner/"Collin Bread Basket" from Pier One'),
(16,'Decorative Lantern','4','IMG_46761753741747.8221333.jpeg','2025-07-28',1,'Red/Six-sided/Metal/Candle Holder/Ring for Hanging'),
(17,'Glass Jar with Pom Pom Balls','4','IMG_46771753742056.4643462.jpeg','2025-07-28',1,'Anchor Hocking/Brushed Metal Lid/1.5 Gallon/Red/White/Blue'),
(18,'Set of Four Glass Jars with Pom Pom Balls','5','IMG_46781753825208.2252505.jpeg','2025-07-29',1,'Anchor Hocking/Brushed Metal Lids/64 Ounce/Red/White/Blue'),
(19,'Set of Three Faux Peony Arrangements in Glass Vases','6','IMG_46791753912464.7088022.jpeg','2025-07-30',1,'Square Vases/Twelve Peonies/Floral/Botanical'),
(20,'Faux Magnolia Arrangement in Glass Vase','6','IMG_46801753912704.477641.jpeg','2025-07-30',1,'Faux Water (discolored)/Floral/Botanical'),
(21,'Faux Rose Arrangement in Glass Vase','6','image1753913098.310538.jpg','2025-07-30',1,'Green Glass/Faux Water/Floral/Botanical'),
(22,'5x7 Set of Three Black Frames','7','IMG_46861754080330.744066.jpeg','2025-08-01',2,'5x7 Matted Opening/Wood/Portrait Wall Frame'),
(23,'Embroidered Table Runner','7','IMG_46881754080796.9677367.jpeg','2025-08-01',1,'Floral/Botanical/Green/Yellow/Teal/Coral/Pier One'),
(24,'A and Z Bookends','7','IMG_46891754081074.1137912.jpeg','2025-08-01',1,'White/Wood'),
(25,'Venetian Glass Flower','7','IMG_46901754081330.6008267.jpeg','2025-08-01',1,'Teal/Purchased in Venice by Evelyn/Floral/Botanical'),
(23542630,'6” Wood Letters','8','image1782579408.5969634.jpg','2026-06-25',2,'Antique White with Decorative Edge'),
(23542631,'Milk Bottle Vase','8','image1782503188.1309478.jpg','2026-06-26',1,'Clear/Glass/Height: 11"'),
(23542632,'7-Piece Glass Flower Vase with Metal Holder','8','image1782579498.5367258.jpg','2026-06-26',1,'Length: 19"/Bottle Height: 4"'),
(23542633,'Pocket Watch Clock','8','image1782504420.4123294.jpg','2026-06-26',1,'Pottery Barn/Pewter Finish/Roman Numerals/Desktop Display/Height: 8"/Diameter: 5.5"'),
(23542634,'Set of Two Decorative Book Boxes','8','image1782579616.94886.jpg','2026-06-26',1,'Floral Folk Art Design with Animals/Yellow/Green'),
(23542635,'Small Pocket Watch Clock','8','image1782508691.4932365.jpg','2026-06-26',1,'Bronze Finish/Desktop Display/Height: 4.5"/Diameter: 3.75"'),
(23542636,'Autumn Kiss Papercut','8','image1782579986.3501115.jpg','2026-06-27',2,'By Artist Tina Tarnoff/15.5"x12.5" Frame'),
(23542637,'8x10 Set of Four Wood Frames','9','image1782596593.606406.jpg','2026-06-27',2,'Landscape or Portrait Frame'),
(23542638,'Arc de Triomphe LEGO Architecture Set','9','image1782596956.9751353.jpg','2026-06-27',1,'21036/Display Set'),
(23542639,'London LEGO Architecture Set','9','image1782597511.431404.jpg','2026-06-27',1,'21034/Display Set'),
(23542640,'Sydney LEGO Architecture Set','9','image1782610559.6158695.jpg','2026-06-28',1,'21032/Display Set'),
(23542641,'Paris LEGO Architecture Set','9','image1782610778.6528494.jpg','2026-06-28',1,'21044/Display Set'),
(23542642,'Trafalgar Square LEGO Architecture Set','9','image1782611065.0024445.jpg','2026-06-28',1,'21045/Display Set');

SET FOREIGN_KEY_CHECKS=1;

